"""add firebase uid to users

Revision ID: a23753a30eb2
Revises: b6b60c6c77f8
Create Date: 2026-10-08 11:24:21.175676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23753a30eb2'
down_revision: Union[str, Sequence[str], None] = 'b6b60c6c77f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('USER', 'AGENT', name='messagerole'),
               existing_nullable=False)
    op.add_column('users', sa.Column('firebase_uid', sa.String(length=128), nullable=False))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'firebase_uid')
    op.alter_column('messages', 'role',
               existing_type=sa.Enum('USER', 'AGENT', name='messagerole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
